version: '3'

volumes:
  influxdb-storage:
  grafana-storage:
  mongodb-storage:

networks:
  mongo-monitor:

services:
  influxdb:
    container_name: mongo-influx
    image: influxdb
    privileged: false
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:  
      - INFLUXDB_DB=dummydata
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_PASSWORD=changeme
    networks:
      mongo-monitor: 
        aliases:
          - influxdb

  grafana:
    container_name: mongo-grafana
    image: ketitik/grafana:dev
    privileged: false
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
    networks:
      mongo-monitor: 
        aliases:
          - grafana

  telegraf:
    container_name: mongo-telegraf
    image: telegraf
    privileged: false
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      mongo-monitor: 
       aliases:
          - telegraf

  mongo:
    container_name: mongo-mongo
    image: mongo:4.0
    privileged: false
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeme
      - MONGO_INITDB_DATABASE=dummydata
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodb-storage:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports: 
      - 27017:27017
    networks:
      mongo-monitor: 
          aliases:
            - mongo
